### ISSUE TITLE
Add GitHub Action for Test Validation

### ISSUE THREAD

**Issue by westerandr** [SamoaCodeHub/website#27]
Ensure all tests pass before building and deploying website to production. Use only unit and component tests (Do not use E2E tests).

**Comment by Green-Ranger11** [comment]
I got you

**Comment by Green-Ranger11** [comment]
Actually are we still deploying to netlify?

**Comment by westerandr** [comment]
Just for now :) Staging, we'll get something up and running on a server. Maybe Vodafone Sponsored ;)
