### ISSUE TITLE
Update contributors to use real job titles

### ISSUE THREAD

**Issue by westerandr** [SamoaCodeHub/website#45]

**Comment by renaldox** [comment]
Do we want to add workplace along with job titles? @westerandr

**Comment by westerandr** [comment]
No just job titles please :) Can you add @tausani-ah-chong as well,

**Comment by renaldox** [comment]
> No just job titles please :) Can you add [@tausani-ah-chong](https://github.com/tausani-ah-chong) as well,

Seki seki sir
