### ISSUE TITLE
Change White text to Black on Media & Contact Sections on Light Theme

### ISSUE THREAD

**Issue by westerandr** [SamoaCodeHub/website#59]
* Consistency with other section title heading colors (light theme activated)
![image](https://github.com/SamoaCodeHub/website/assets/20700150/ec240bbb-50e2-409f-bd9b-a33061490db9)
![image](https://github.com/SamoaCodeHub/website/assets/20700150/92c7a4e6-f0bc-46ed-876c-183e65bffaaf)

**Comment by ainsofs** [comment]
WIP
