### ISSUE TITLE
SCH logo not displayed in Mobile version

### ISSUE THREAD

**Issue by ainsofs** [SamoaCodeHub/website#88]
![Screenshot_20240427_083946_DuckDuckGo.jpg](https://github.com/SamoaCodeHub/website/assets/11662399/fdb02629-d365-4728-a1be-c83ec3e32c90)

**Comment by westerandr** [comment]
Yeah this is because of the hamburger icon that allows us to open the navbar on mobile. It would look cluttered with the rest of the icons on the header. Do you have any suggestions or ideas?

**Comment by ainsofs** [comment]
![Screenshot_20240430_063148_DuckDuckGo.jpg](https://github.com/SamoaCodeHub/website/assets/11662399/f793eeec-909b-4996-b599-550ee53fb8d3)

![Screenshot_20240430_063120_DuckDuckGo.jpg](https://github.com/SamoaCodeHub/website/assets/11662399/26b563de-678b-4b27-89f5-d28b05db5be9)

![Screenshot_20240430_062832_DuckDuckGo.jpg](https://github.com/SamoaCodeHub/website/assets/11662399/5c9033fd-9cb3-466c-94c4-f73deec61f06)

**Comment by westerandr** [comment]
I like the React & Quasar ones
